### ISSUE TITLE
Missing dependency (pg) in npm package

### ISSUE THREAD

**Issue by thomas-picariello** [chilts/koa-pg#10]
The package uploaded to npm is not mentioning the `pg` dependency.
https://www.npmjs.com/package/koa-pg

**Comment by chilts** [comment]
This project is no longer maintained. Feel free to fork or I can give you permissions both here and on npm to patch and publish. Let me know if you'd like that.

**Comment by thomas-picariello** [comment]
Solved by #9 .

**Comment by chilts** [comment]
Thanks for closing. :)
