### ISSUE TITLE
co-pg dependency out of date

### ISSUE THREAD

**Issue by whodidthis** [chilts/koa-pg#2]
Not sure if 0.1.1 found on npm anymore.

This is awesome btw

**Comment by chilts** [comment]
I think this is done in #5.

**Comment by matthewdias** [comment]
needs update to co-pg 2.0.0.

**Comment by chilts** [comment]
Feel free to fork this, or am happy to add you or anyone as a contributor or maintainer. I'm not maintaining this repo anymore.

**Comment by chilts** [comment]
Hmm, sorry about that comment. Someone must have left a comment then deleted it, since I have it on email, The comment read:

"needs update to co-pg 2.0.0."
