### ISSUE TITLE
This is package is fundamentally broken, and it's also the only postgresql middleware for koa

### ISSUE THREAD

**Issue by crimsonalucard** [chilts/koa-pg#5]
Does not compile with anything greater then node 0.11.12

as a temporary work around in a build script I use nvm to revert node to v0.11.12 before installing this script.

In short, I leave koa-pg out of package.json and run these is a shell script:

npm install
n 0.11.12
npm install koa-pg
n 0.12

When running the server I run it with node 0.12. It passes all my unit tests so it should be fine.

**Comment by chilts** [comment]
Thanks for raising this issue. I'm not using this package, but I'd be happy to take PRs and re-release to npm. Alternatively, I can add you as a contributor here and npmjs.org if you'd like more control?

**Comment by crimsonalucard** [comment]
Yeah! I'd be happy to contribute here and on npmjs.org. Thanks!

**Comment by timhaak** [comment]
Hi

Just sent a pull request with the updates.

https://github.com/chilts/koa-pg/pull/6

**Comment by chilts** [comment]
Thanks. I'll close this when I release to npm and report back here when it's done. I presume you guys want me to release it pretty soon? Or is there anything else that needs doing to make the package better?

**Comment by crimsonalucard** [comment]
looks good to me. Thanks!

**Comment by chilts** [comment]
v0.24.0 released. Thanks @timhaak and @crimsonalucard.

* https://www.npmjs.com/package/koa-pg
