### ISSUE TITLE
Listen / notify

### ISSUE THREAD

**Issue by epoberezkin** [chilts/koa-pg#7]
Is it possible to subscribe to notifications with this library? Thanks

**Comment by chilts** [comment]
Hiya. I'm not actively maintaining this repo since I'm not using Koa, but I am happy to take PRs to add additional features.

And to be honest, I don't know what notifications you're talking about. :)

**Comment by epoberezkin** [comment]
Thanks. I meant NOTIFY / LISTEN of Postgres. It seems using pg for it is more convenient...

**Comment by chilts** [comment]
Awesome. Thanks. Yeah, that's probably a better plan than this. :)
